spring:
  application:
    name: kafka-sendgrid
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka-external.kafka.svc.cluster.local:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:form137-sendgrid-consumer}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      enable-auto-commit: false
    topic:
      name: ${KAFKA_TOPIC_NAME:form137-email-notifications}

sendgrid:
  api-key: ${SENDGRID_API_KEY:your-sendgrid-api-key}
  from-email: ${SENDGRID_FROM_EMAIL:no-reply@yourdomain.com}
  from-name: ${SENDGRID_FROM_NAME:Form 137 System}
  templates:
    use-templates-by-default: ${SENDGRID_USE_TEMPLATES:true}
    default-template-id: ${SENDGRID_DEFAULT_TEMPLATE_ID:}
    ids:
      submission: ${SENDGRID_TEMPLATE_SUBMISSION:d-xxx-submission-template-id}
      status_update: ${SENDGRID_TEMPLATE_STATUS_UPDATE:d-xxx-status-update-template-id}
      approval: ${SENDGRID_TEMPLATE_APPROVAL:d-xxx-approval-template-id}
      rejection: ${SENDGRID_TEMPLATE_REJECTION:d-xxx-rejection-template-id}
      reminder: ${SENDGRID_TEMPLATE_REMINDER:d-xxx-reminder-template-id}
      completion: ${SENDGRID_TEMPLATE_COMPLETION:d-xxx-completion-template-id}

logging:
  level:
    ph.edu.cspb.kafkasendgrid: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized