spring:
  application:
    name: kafka-sendgrid
  
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:kafka-sendgrid-group}
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:earliest}
      enable-auto-commit: false
    topic:
      name: ${KAFKA_TOPIC_NAME:sendgrid-topic}

sendgrid:
  api-key: ${SENDGRID_API_KEY:your-sendgrid-api-key}
  from-email: ${SENDGRID_FROM_EMAIL:no-reply@yourdomain.com}

logging:
  level:
    ph.edu.cspb.kafkasendgrid: INFO
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized